trigger:
- test2

pool: Default

steps:
- script: echo Hellgfhjo, world!
  displayName: 'Run a onjddjjjyughuehgdjjyiou,,yuo8oip6t'

- script: |
    echo Add other tasks to bujihbuygld, atest, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
